<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { Check, Download, ExternalLink, Plus, Search, ShieldAlert, Square, X } from "@lucide/vue";
import { api } from "../api";
import type { Asset, ExposureFinding, ExposureRun, ExposureSourceResult, ExposureSummary, Project } from "../types";
import "../exposure-surface.css";
import "../exposure-runs.css";
import "../exposure-tabs.css";

const props=defineProps<{projects:Project[];selectedProjectId?:number}>();
const emit=defineEmits<{notify:[type:"success"|"error"|"info",text:string]}>();
const blank=():ExposureSummary=>({eligibleAssets:0,total:0,newCount:0,reviewing:0,confirmed:0,dismissed:0,highRisk:0});
const summary=ref(blank()),findings=ref<ExposureFinding[]>([]),status=ref(""),search=ref(""),loading=ref(false),showAdd=ref(false),saving=ref(false);
const runs=ref<ExposureRun[]>([]);let pollTimer:ReturnType<typeof setInterval>|undefined;
const sources=ref<ExposureSourceResult[]>([]),eligibleAssets=ref<Asset[]>([]),view=ref<"overview"|"runs"|"findings"|"sources">("overview");
const form=ref<{assetId?:number;category:string;title:string;sourceType:string;sourceUrl:string;evidenceExcerpt:string;severity:string;confidence:number}>({category:"source_code",title:"",sourceType:"public_web",sourceUrl:"",evidenceExcerpt:"",severity:"medium",confidence:70});
const project=computed(()=>props.projects.find(item=>item.id===props.selectedProjectId));
const categoryLabel=(v:string)=>({source_code:"源代码泄漏",document:"内部文档",credential:"凭据线索",storage:"公开存储",repository:"代码仓库",metadata:"敏感元数据",other:"其他"} as Record<string,string>)[v]||v;
const activeRun=computed(()=>runs.value.find(run=>["queued","running"].includes(run.status)));
async function load(){if(!props.selectedProjectId){summary.value=blank();findings.value=[];runs.value=[];sources.value=[];eligibleAssets.value=[];return}loading.value=true;try{const [nextSummary,nextFindings,nextRuns,assetPage]=await Promise.all([api.exposureSummary(props.selectedProjectId),api.listExposureFindings(props.selectedProjectId,status.value,search.value),api.listExposureRuns(props.selectedProjectId),api.listAssets({projectId:props.selectedProjectId,search:"",conditions:[],page:1,pageSize:500,includeDeleted:false,deletedView:"active",probeView:"all",probeOutcomeView:"all",sentinelView:"all",decisionView:"all",ownershipView:"eligible",sortBy:"priority",sortDirection:"desc"})]);summary.value=nextSummary;findings.value=nextFindings;runs.value=nextRuns;eligibleAssets.value=assetPage.items;sources.value=nextRuns[0]?await api.listExposureSourceResults(nextRuns[0].id):[]}catch(e){emit("notify","error",String(e))}finally{loading.value=false}}
async function startScan(){if(!props.selectedProjectId||activeRun.value)return;try{const id=await api.startExposureScan(props.selectedProjectId);emit("notify","success",`被动采集任务 #${id} 已启动`);await load()}catch(e){emit("notify","error",String(e))}}
async function save(){if(!props.selectedProjectId||saving.value)return;saving.value=true;try{await api.saveExposureFinding({...form.value,projectId:props.selectedProjectId});showAdd.value=false;form.value={category:"source_code",title:"",sourceType:"public_web",sourceUrl:"",evidenceExcerpt:"",severity:"medium",confidence:70};emit("notify","success","公开暴露线索已归并保存");await load()}catch(e){emit("notify","error",String(e))}finally{saving.value=false}}
async function cancelRun(){if(!activeRun.value)return;try{await api.cancelExposureScan(activeRun.value.id);emit("notify","info","已请求取消，已采集结果会保留");await load()}catch(e){emit("notify","error",String(e))}}
async function exportFindings(){if(!props.selectedProjectId)return;try{const result=await api.exportExposureFindings(props.selectedProjectId);emit("notify","success",`已导出 ${result.rows} 条：${result.path}`)}catch(e){emit("notify","error",String(e))}}
async function review(item:ExposureFinding,next:string){try{await api.reviewExposureFinding(item.id,next,item.note||"");await load()}catch(e){emit("notify","error",String(e))}}
watch(()=>props.selectedProjectId,load);onMounted(()=>{void load();pollTimer=setInterval(()=>{if(activeRun.value)void load()},2500)});onUnmounted(()=>{if(pollTimer)clearInterval(pollTimer)});
</script>

<template><div class="exposure-surface">
  <div class="section-toolbar"><div><span class="eyebrow">PUBLIC EXPOSURE</span><h2>公开暴露面</h2><p>网站、证书透明度与历史归档统一采集；只接受已通过归属与授权门禁的资产。</p></div><div><button v-if="activeRun" class="button danger" @click="cancelRun"><Square :size="14"/>停止采集</button><button v-else class="button ghost" :disabled="!project" @click="startScan"><Search :size="15"/>开始完整采集</button><button class="button ghost" @click="exportFindings"><Download :size="15"/>导出</button><button class="button primary" :disabled="!project" @click="showAdd=!showAdd"><Plus :size="15"/>录入线索</button></div></div>
  <div v-if="!project" class="panel exposure-empty"><ShieldAlert :size="25"/><strong>请先选择工作空间</strong><span>暴露面线索不能跨公司混合。</span></div>
  <template v-else>
    <nav class="exposure-tabs"><button :class="{active:view==='overview'}" @click="view='overview'">总览</button><button :class="{active:view==='runs'}" @click="view='runs'">采集任务</button><button :class="{active:view==='findings'}" @click="view='findings'">线索复核</button><button :class="{active:view==='sources'}" @click="view='sources'">数据源</button></nav>
    <section v-if="view==='overview'" class="exposure-summary"><button @click="status='';view='findings';load()"><span>准入资产</span><strong>{{summary.eligibleAssets}}</strong></button><button @click="status='new';view='findings';load()"><span>新线索</span><strong>{{summary.newCount}}</strong></button><button @click="status='reviewing';view='findings';load()"><span>复核中</span><strong>{{summary.reviewing}}</strong></button><button @click="status='confirmed';view='findings';load()"><span>已确认</span><strong>{{summary.confirmed}}</strong></button><button class="risk" @click="view='findings'"><span>高风险待处置</span><strong>{{summary.highRisk}}</strong></button></section>
    <section v-if="view==='runs'&&runs.length" class="panel exposure-runs"><div v-for="run in runs" :key="run.id"><strong>#{{run.id}} · {{run.status}}</strong><span>{{run.stage}}<template v-if="run.currentSource"> · {{run.currentSource}}</template> · {{run.scannedAssets}} / {{run.eligibleAssets}} 资产 · {{run.fetchedResources}} 资源 · {{run.findings}} 新线索</span><small v-if="run.error">{{run.error}}</small></div></section>
    <section v-if="view==='sources'" class="panel exposure-runs"><div v-for="source in sources" :key="source.sourceKey"><strong>{{source.sourceKey}} · {{source.status}}</strong><span>{{source.itemCount}} 条结果 · {{source.completedAt}}</span><small v-if="source.error">{{source.error}}</small></div><div v-if="!sources.length">尚无数据源执行记录</div></section>
    <section v-if="showAdd" class="panel exposure-add"><header><strong>录入或导入公开线索</strong><button @click="showAdd=false"><X :size="16"/></button></header><div class="exposure-form"><label><span>绑定准入资产（可选）</span><select v-model="form.assetId"><option :value="undefined">主体级线索</option><option v-for="asset in eligibleAssets" :key="asset.id" :value="asset.id">{{asset.domain||asset.host||asset.link}}</option></select></label><label><span>类型</span><select v-model="form.category"><option value="source_code">源代码泄漏</option><option value="document">内部文档</option><option value="credential">凭据线索</option><option value="storage">公开存储</option><option value="repository">代码仓库</option><option value="metadata">敏感元数据</option><option value="other">其他</option></select></label><label><span>风险</span><select v-model="form.severity"><option value="low">低</option><option value="medium">中</option><option value="high">高</option><option value="critical">严重</option></select></label><label class="wide"><span>标题</span><input v-model="form.title" placeholder="面向复核人员的清晰描述"/></label><label class="wide"><span>公开来源 URL</span><input v-model="form.sourceUrl" placeholder="https://…"/></label><label class="wide"><span>证据摘要（不要粘贴完整密钥）</span><textarea v-model="form.evidenceExcerpt" rows="4" placeholder="记录文件路径、字段名、脱敏片段和可复现位置"></textarea></label></div><footer><button class="button primary" :disabled="saving" @click="save">保存并自动去重</button></footer></section>
    <section v-if="view==='overview'||view==='findings'" class="panel exposure-list"><header><div><strong>暴露线索</strong><small>{{findings.length}} 条当前结果</small></div><label><Search :size="14"/><input v-model="search" placeholder="搜索标题、来源或证据" @keyup.enter="load"/></label></header><article v-for="item in findings" :key="item.id"><div class="exposure-risk" :class="item.severity">{{item.severity}}</div><div class="exposure-main"><div><span>{{categoryLabel(item.category)}}</span><strong>{{item.title}}</strong><em>{{item.confidence}}% 可信度</em></div><a :href="item.sourceUrl" target="_blank">{{item.sourceUrl}} <ExternalLink :size="11"/></a><p>{{item.evidenceExcerpt||'尚未填写证据摘要'}}</p><small>{{item.assetLabel||'主体级公开线索'}} · {{item.sourceType}} · 首次 {{item.firstSeenAt}} · 最近 {{item.lastSeenAt}}</small></div><div class="exposure-actions"><span :class="`status-${item.status}`">{{item.status}}</span><button @click="review(item,'reviewing')">复核</button><button class="confirm" @click="review(item,'confirmed')"><Check :size="12"/>确认</button><button @click="review(item,'dismissed')"><X :size="12"/>排除</button></div></article><div v-if="loading" class="exposure-empty">正在加载…</div><div v-else-if="!findings.length" class="exposure-empty">当前筛选没有公开暴露线索</div></section>
  </template>
</div></template>
